package com.sohu.inputmethod.sogou;

/**
 * Created by Qiao on 2018/12/24.
 */
public interface Constants {
    String KEY_CURRENT_WORD = "KEY_CURRENT_WORD";
    String KEY_TIMESTAMP_SEARCH = "KEY_TIMESTAMP_SEARCH";
    String KEY_TIMESTAMP_ASSIST = "KEY_TIMESTAMP_ASSIST";
    String KEY_WORDS_LIST = "KEY_WORDS_LIST";
    String KEY_FAVORITE_LIST = "KEY_FAVORITE_LIST";
    String KEY_FIRST_TIP_SHOWN = "KEY_FIRST_TIP_SHOWN";
    String KEY_GIF_SOURCE = "KEY_GIF_SOURCE";

    String KEY_SETTING_PAGE_SIZE = "KEY_SETTING_PAGE_SIZE";
    String KEY_SETTING_EXPAND_HISTORY = "KEY_SETTING_EXPAND_HISTORY";
    String KEY_SETTING_REMEMBER_LAST = "KEY_SETTING_REMEMBER_LAST";
    String KEY_SETTING_AUTO_ASSIST = "KEY_SETTING_AUTO_ASSIST";
    String KEY_SETTING_AUTO_FAVORITE = "KEY_SETTING_AUTO_FAVORITE";
    String KEY_SETTING_IS_FAVORITE = "KEY_SETTING_IS_FAVORITE";

    String INTENT_ACTION_RESTORE = "INTENT_ACTION_RESTORE";
}
